"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("fs");
var path = require("path");
var fileParser_1 = require("./fileParser");
var dataFilePath = path.join(__dirname, "./data/example1.js");
var data = fs.readFileSync(dataFilePath, "utf-8");
var newData = (0, fileParser_1.parseFile)(data);
console.log(newData);
// const outputFilePath = path.join(__dirname, "./data/example1-tokenized.txt");
// fs.writeFileSync(outputFilePath, newData.toString());
